# Generated by Django 4.0.6 on 2022-07-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('premiere_date', models.DateField()),
                ('review', models.IntegerField(choices=[(1, 'Like It'), (2, 'Love It'), (3, 'Gotta Have It')])),
            ],
        ),
    ]
